### ISSUE TITLE
Inference Time Details

### ISSUE THREAD

**Issue by animesh-s** [google/break-a-scene#10]
Really great work! I couldn't find the inference time details in the paper around these two topics:

1. Since the Unet is finetuned for all concepts at once, is it fair to say that we don't need to maintain a "copy" of Unet for each concept? So the extra cost of storage per concept/user is close to none?
2. How does the inference speed compare to other methods like Dreambooth and HyperDreamBooth, etc?

**Comment by omriav** [comment]
Hi,
1. Yes -- all the concepts are being encapsulated in the UNet, s.t there is not additional storage cost per concept.
2. It is the same as the standard diffusion inference (same as DreamBooth and Textual Inversion)
