### ISSUE TITLE
Improved Generation of Celebrity Images Compared to Other Humans as Concepts?

### ISSUE THREAD

**Issue by whiterose199187** [google/break-a-scene#13]
Given the abundance of high-quality and diverse images of celebrities available for training, is it plausible that the model might generate better or more accurate images of celebrities (extracted as a concept during training) compared to other less photographed or publicized individuals?

In my tests when I used an image where one of the concepts was a celebrity, my image generation results have 3/5 images where the generated image looks exactly like the human concept. I see similar result when I used an image from VITON-HD dataset but when using my personal image the generated images do not have any likeness to my face at all

Is this expected behavior? If so, does that mean that using LoRA for fine-tuning is a better fit for this use case?

Any insights or references to related work would be highly appreciated. Thank you for your time and consideration!

**Comment by omriav** [comment]
Hi,
I have not personal experience with that.
Maybe you should try a bit longer training on the second phase, by setting `--phase2_train_steps` to a higher number (e.g., 600).

**Comment by whiterose199187** [comment]
Hello, 

I will try that and report back

Meanwhile, just so I understand correctly when you say:

>>  I have not personal experience with that.

Does that mean that this is not something you tried or that it is something you've tried and in your experience the results are good?

Thanks

**Comment by omriav** [comment]
Hi,
I did not try that.

**Comment by whiterose199187** [comment]
Hello,


I tried with phase2_train_steps = 600 and got better results but it's still not there. I am now thinking of trying different fine-tuned SD models and give it a shot. Any other params you would suggest I play around with and try?
