### ISSUE TITLE
error when using stabilityai/stable-diffusion-2-1 to train

### ISSUE THREAD

**Issue by whiterose199187** [google/break-a-scene#14]
Hello,

When using `stabilityai/stable-diffusion-2-1` to train instead of `stabilityai/stable-diffusion-2-1-base` I get the following error:

`Traceback (most recent call last):
  File "/root/break-a-scene/train.py", line 1524, in <module>
    SpatialDreambooth()
  File "/root/break-a-scene/train.py", line 627, in __init__
    self.main()
  File "/root/break-a-scene/train.py", line 1152, in main
    model_pred = model_pred * downsampled_mask
RuntimeError: The size of tensor a (96) must match the size of tensor b (64) at non-singleton dimension 3` 

I made sure that input image and masks are 768 x 768 (same as the class images generated by `stabilityai/stable-diffusion-2-1`)

Please share any suggestions on how I can debug/fix this.

Thanks

**Comment by omriav** [comment]
Hi,
The masks should not be of `768x768` resolution, they should match the resolution of the latent space (which is lower dimensional).
In the case of the `base` model, the resolution is `64x64`.
So I think that in your case the mask should be resized to `96x96`.

**Comment by whiterose199187** [comment]
Thanks for your response, I will try this.

> The masks should not be of 768x768 resolution, they should match the resolution of the latent space (which is lower dimensional).

When training using the base model, I always used image/mask of size 512x512 and it works fine. Even the examples at https://github.com/google/break-a-scene/tree/main/examples/creature are of size 512x512. 

Am I misunderstanding something?

**Comment by omriav** [comment]
You should change the code to downsample the mask to the relevant latent space size `96x96` from what I understand, in all the relevant places: [here](https://github.com/google/break-a-scene/blob/135cd4a40e117efb80175db7ca5c0ea44e514ca8/train.py#L1150), [here](https://github.com/google/break-a-scene/blob/135cd4a40e117efb80175db7ca5c0ea44e514ca8/train.py#L1175) and [here](https://github.com/google/break-a-scene/blob/135cd4a40e117efb80175db7ca5c0ea44e514ca8/train.py#L1411)

**Comment by whiterose199187** [comment]
Hello,

I made those changes and I get the below error:

`Traceback (most recent call last):
  File "/root/break-a-scene/train.py", line 1524, in <module>
    SpatialDreambooth()
  File "/root/break-a-scene/train.py", line 627, in __init__
    self.main()
  File "/root/break-a-scene/train.py", line 1190, in main
    agg_attn = self.aggregate_attention(
  File "/root/break-a-scene/train.py", line 1402, in aggregate_attention
    out = torch.cat(out, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors`

Are there any other changes I should make? Thanks in advance for your help!

**Comment by omriav** [comment]
You should also change the attentions maps that are being used [here](https://github.com/google/break-a-scene/blob/135cd4a40e117efb80175db7ca5c0ea44e514ca8/train.py#L1188) to the relevant size, I think it should be `(24, 24)`

**Comment by whiterose199187** [comment]
I tried that earlier, I get the following error:

`Traceback (most recent call last):
  File "/root/break-a-scene/train.py", line 1524, in <module>
    SpatialDreambooth()
  File "/root/break-a-scene/train.py", line 627, in __init__
    self.main()
  File "/root/break-a-scene/train.py", line 1190, in main
    agg_attn = self.aggregate_attention(
  File "/root/break-a-scene/train.py", line 1402, in aggregate_attention
    out = torch.cat(out, dim=0)
RuntimeError: torch.cat(): expected a non-empty list of Tensors`

**Comment by omriav** [comment]
I understand, so you need to check the size of the most semantic cross-attention maps in this model (I know that in the standard `512x512` model, the most semantic cross-attention maps are `16x16`). Then, calculate the average cross-attention map over this resolution.

Unfortunately, I do not have time to do it myself, sorry that I cannot help more than that.
