### ISSUE TITLE
Concept extraction issue

### ISSUE THREAD

**Issue by chester256** [google/break-a-scene#15]
I have tried many examples, and it worked fine. However, sometimes the model fails to extract the concept and "mixes" the concept into a single token. For example, consider the "rabbit" case in the example directory. After training, the prompt "a photo of a \<asset0\>" still gives the photo of both \<asset0\> and \<asset1\>, as shown below:
![image](https://github.com/google/break-a-scene/assets/18751402/25557426-f17f-405b-9cc3-ee389e2d03a8)

I found that training for fewer steps in phase 2 could help sometimes, but it doesn't always help. Do you have any suggestions to address the concept extraction failure cases?

**Comment by omriav** [comment]
Hi,

You can try to mitigate this problem by:
1. Reducing phase 2 training steps (as you said), you can increase the phase 1 training steps instead.
2. Increasing the coefficient of the cross-attention loss (`--lambda_attention`)
3. Use better `--initializer_tokens` (in case you did not use them)

Hope it helps.

Omri

**Comment by chester256** [comment]
It works in some cases. Thanks!

**Comment by shaswati1** [comment]
Hi @chester256 , could you share your environment file? It takes forever for me to create the environment with the provided yml file and in the end, it gets killed without creating one! :(

Update: Fixed.
