### ISSUE TITLE
Separate two anime characters

### ISSUE THREAD

**Issue by ainiyo-wj** [google/break-a-scene#16]
hello， I have tried many times to Separate two anime characters, including increase  or reduce the steps of phase 2, or enlarge the  lambda_attention（0.01-0.05-0.1）, but  I always failed. can you give me some advice.

**Comment by omriav** [comment]
Hi,
I share some tips [here](https://github.com/google/break-a-scene/issues/15#issuecomment-1790647913).
Maybe try using better initializing tokens.
