### ISSUE TITLE
Question about the tool for generating masks

### ISSUE THREAD

**Issue by Correr-Zhou** [google/break-a-scene#17]
Hi there,

Great work! I am curious about how to generate masks for this method in a convenient way. It would be helpful if you could provide the details of the tool you used for generating masks. Is it an off-the-shelf segmentation model or a manual labeling tool?

**Comment by omriav** [comment]
Hi,

You can use any pre-trained segmentation model (e.g., [Segment Anything](https://github.com/facebookresearch/segment-anything)).
You can also do it manually, because the segmentation masks can be coarse.

Omri
