### ISSUE TITLE
Question about background extraction

### ISSUE THREAD

**Issue by kkang831** [google/break-a-scene#18]
Thank you for sharing the excellent work. 

After all the training process, what is the token that refers to the background? How can I extract the background?
I might have missed it in the code, but it seems there is no step to register a background token.

Do I need to add it myself, like other assets?

**Comment by omriav** [comment]
Hi,

Yes --- you can treat the background as any other asset, by providing a mask and (optionally) an initializer token.

**Comment by kkang831** [comment]
Ah-ha I fully understand it. Thank you
