### ISSUE TITLE
The dataset images in Break-A-Scene.

### ISSUE THREAD

**Issue by Tchuanm** [google/break-a-scene#19]
Hi, Thanks for your great work.

Could you release the dataset images or selection scripts from CoCO in our paper ?

As I heard in the paper, there are 5400 imges per baseline.

**Comment by billpsomas** [comment]
Hello,

I am also interested on this dataset. Is there someone publicly available? Can you provide me with a link?

Thanks a lot!!!

**Comment by Tchuanm** [comment]
No, I don't get any dataset.

**Comment by omriav** [comment]
Hi,

I'm sorry but I have no longer access to the extracted COCO dataset.

Omri

**Comment by billpsomas** [comment]
Hello Omri,

Thanks for getting back so quickly.

Okay, I understand. Thanks for letting know!
