### ISSUE TITLE
Learning concepts from multiple images

### ISSUE THREAD

**Issue by mvp18** [google/break-a-scene#21]
Hi,

Thanks for your great work. The instructions mentioned having a single image in the `instance_data_dir` folder and the corresponding masks. But, I was wondering if there was a way to learn concepts corresponding to fixed no. of masks across multiple images such that the mask ids across images correspond to the same object/background, but viewed from different viewpoints. The original textual_inversion method. for example, allows learning a single concept from multiple images, but of course, without masks.

I look forward to your reply.

**Comment by omriav** [comment]
Hi,

The current codebase does not support it, however, in principle, our method can be extended to this scenario (with some code adaptations).

Omri

**Comment by mvp18** [comment]
Hi Omri,

Thanks for the reply. Just out of curiosity, do you think that would potentially alleviate the pose fixation and restriction to max 4 concepts in an image you mention in the limitations section of the paper?

**Comment by omriav** [comment]
Hi,

I believe that it will mitigate the "pose fixation" problem (as the input will be more diverse).
Regarding the number of supported concepts - I am not so sure.

Best,
Omri

**Comment by mvp18** [comment]
Thanks for your insights :)

**Comment by omriav** [comment]
Sure :)
