### ISSUE TITLE
GPU Memory Requirements for Training

### ISSUE THREAD

**Issue by CyberDragon93** [google/break-a-scene#22]
I want to express my appreciation for your outstanding work on this project! 

I'm curious about the minimum GPU memory requirements for training and whether multi-GPU training is supported for handling the model.

Thank you for your time and assistance!

**Comment by omriav** [comment]
Hi,

I used a single A100 40G NVIDIA GPU, but I didn't try to use more than that.
There may be some minor code changes to support multi-GPU training, but, I am not sure.

Best,
Omri
