### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by rezkanas** [google/break-a-scene#23]
using the arguments below:

`python3 /home/anasrezklinux/test_pycharm_link/main/break_a_scene/break_a_scene_git_repository/train.py --instance_data_dir /mnt/c/Users/noobw/PycharmProjects/pythonProject/photos/break_scene_photo --num_of_assets 2 --initializer_tokens ['person', 'person'] --class_data_dir /home/anasrezklinux/test_pycharm_link/main/break_a_scene/person --phase1_train_steps 12 --phase2_train_steps 12 --use_8bit_adam --gradient_accumulation_steps 2 --enable_xformers_memory_efficient_attention --output_dir /home/anasrezklinux/test_pycharm_link/main/break_a_scene`

I am having the following OOM error: 

`OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB. GPU 0 has a 
total capacity of 12.00 GiB of which 0 bytes is free. Process 162525 has 
17179869184.00 GiB memory in use. Including non-PyTorch memory, this process has
17179869184.00 GiB memory in use. Of the allocated memory 17.76 GiB is allocated
by PyTorch, and 315.99 MiB is reserved by PyTorch but unallocated. If reserved 
but unallocated memory is large try setting 
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See 
documentation for Memory Management `

do you have any suggestion to how could I circumvent this? I have 12GB VRAM on my GPU.

**Comment by omriav** [comment]
Hi,

Sorry for the late response.
You can use the suggestions from [this issue](https://github.com/google/break-a-scene/issues/11).

Best,
Omri

**Comment by rezkanas** [comment]
I tried to follow all the tricks in that page. i still have the error.

**Comment by omriav** [comment]
Hi,

Please try adding these parameters: `--use_8bit_adam --gradient_checkpointing --enable_xformers_memory_efficient_attention --set_grads_to_none`.
