### ISSUE TITLE
asset understanding

### ISSUE THREAD

**Issue by Sana555-Attar** [google/break-a-scene#25]
@omriav Can you please clarify the below questions 
1.what is asset here, is it text token of each concept? if yes, which format it will store in folder. 
2.training is needed,we cant do direct inference even if we have single concept in each image,right?

"
After training, a new model will be saved in OUTPUT_DIR with an extended vocabulary that contains the additional concepts <asset0> ... <assetN> where N = NUMBER_OF_CONCEPTS - 1. For example, in the above case, there will be additional 3 tokens <asset0>, <asset1> and <asset2>."

**Comment by omriav** [comment]
Hi,

1. An asset is essentially a combination of text token and LoRA weights.
2. Right.

Best,
Omri

**Comment by Sana555-Attar** [comment]
Thanks @omriav
