### ISSUE TITLE
About Masked Loss

### ISSUE THREAD

**Issue by Darth-Zzz** [google/break-a-scene#31]
https://github.com/google/break-a-scene/blob/b142cf2451c5ff2a98ff06b4e56316c49c288d7a/train.py#L1152

Hi, 

It seems you applied a mask directly on the latent space. What is the rationale behind this?

**Comment by omriav** [comment]
Hi,

As the denoising model us a fully-convolutional network, it preserves the proportional spatial correspondence to the input image.
Hence, we can perform the masking on the latent space.

Best,
Omri

**Comment by Darth-Zzz** [comment]
Thanks for your reply!

But isn't the latent space generated by an encoder (VAE) from pixel space? Does this preserve the spatial correspondence?

**Comment by omriav** [comment]
Hi,

Yes --- it preserves the **proportional** spatial correspondence (e.g., the top left entry in the latent space correspond to the top left patch in the pixel space).
This phenomenon was already used in our previous project - [Blended Latent Diffusion](https://omriavrahami.com/blended-latent-diffusion-page/).

**Comment by Darth-Zzz** [comment]
Thanks!
