### ISSUE TITLE
If prior perservation loss is used for the results in the paper?

### ISSUE THREAD

**Issue by LPengYang** [google/break-a-scene#4]
Thanks for your wonderful work. 
It is observed that there are only reconsturction loss and attention map loss in the paper. However, in the provided code, prior perservation loss appears, which requires 100 (default) images for each concept. If prior perservation loss is used for the results presented in the paper. Why this loss has not been mentioned in the paper but appear in the code. Thanks again.

**Comment by omriav** [comment]
Hi,
Yes, we used this default prior preservation loss in our experiments. 
And you are correct, we should have mentioned it in the paper.
However, we did not ablate the importance of this prior preservation loss, so it may be not that important.
