### ISSUE TITLE
Inpainting training and inference

### ISSUE THREAD

**Issue by vinm007** [google/break-a-scene#5]
Thanks for sharing the awesome work.
I am able to train and test the inference of the Text2Image model. How to do the same for the inpainting model?

**Comment by omriav** [comment]
Hi,
Thank you very much for raising it.
I added the instructions on how to incorporate [Blended Latent Diffusion](https://omriavrahami.com/blended-latent-diffusion-page/) into our method in the [README](https://github.com/google/break-a-scene#local-editing-by-example-optional).
