### ISSUE TITLE
[Question] Why using the just half of attention maps?

### ISSUE THREAD

**Issue by Suho0922** [google/break-a-scene#8]
https://github.com/google/break-a-scene/blob/135cd4a40e117efb80175db7ca5c0ea44e514ca8/ptp_utils.py#L104C13-L105C83

h = attn.shape[0]
attn[h // 2 :] = self.forward(attn[h // 2 :], is_cross, place_in_unet)

in here using above h//2 index attention maps are stored. Why are using just above half of attention map?

**Comment by omriav** [comment]
Hi,
The first half of the attention maps is irrelevant: during training, it contains the attention maps for the prior preservation instances (which we do not want to enforce any structure on) and, during inference, it contains the unconditional part of the classifier-free guidance, which is not relevant for the visualization.

I hope it clarifies a bit.

**Comment by Suho0922** [comment]
I see, thank you for clear explanation!

**Comment by omriav** [comment]
Sure, you're welcome.
